version: "3"
services:
  react-app:
    #here we've to specify the location of our Makefile
    build: ./client/
    stdin_open: true
    #here we're mapping the exposed port i.e, 3000 to our machine port 3000.
    # so that we can test the application on our port 3000.
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    #here we've to specify the location of our Makefile
    build: ./api/
    ports:
      - "5000:5000"
    networks:
      - mern-app
    # volumes:
    #   - ./server/:/usr/src/app
    #   - /usr/src/app/node_modules
    # depends_on:
    #   - mongo

    #================ aqui voce pode criar um banco mongo sem usar cluster==================

  # mongo:
  #   #instead of build tag we're using image tag because we're using the official image of MongoDB
  #   #this will pull the official image from the docker hub.
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - mern-app
  #   volumes:
  #     - mongo-data:/data/db
  #   environment:
  #     MONGO_INITDB_DATABASE: testevcodes
          
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local